version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - mailing-network
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_API=http://backend:3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mailing-network
    env_file:
      - .env
    
networks:
  mailing-network:
    driver: bridge